# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 14:33
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(max_length=300, verbose_name='Sub Title')),
                ('content', models.TextField(help_text='Use Markdown syntax.', verbose_name='Entry body')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Entry body as HTML')),
                ('draft', models.BooleanField(default=blog.models.Post.bool_d)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
